### ISSUE TITLE
Lists are handled unintuitively

### ISSUE THREAD

**Issue by moqmar** [alexlafroscia/yaml-merge#12]
```yaml
# first.yml
hello:
- world
- alex

# second.yml
hello:
- moritz

# yaml-merge first.yml second.yml
hello:
- moritz
- alex
```

It makes sense, as `.hello[0]` in `first.yml` gets overwritten with `.hello[0]` from `second.yml`, but when using this to merge e.g. configuration files, most people probably expect something like `["world", "alex", "moritz"]` from that. If someone really wants the second behaviour, you could still allow the following YAML file to override values:

```yaml
hello:
  0: moritz
```

To implement this, there's https://lodash.com/docs/4.17.15#mergeWith:
```javascript
_.mergeWith({}, ...files, (objValue, srcValue, key, object, source, stack) => Array.isArray(objValue) && Array.isArray(srcValue) ? [...objValue, ...srcValue] : undefined)
```
