### ISSUE TITLE
Issues with empty objects

### ISSUE THREAD

**Issue by boesing** [alexlafroscia/yaml-merge#5]
Hey there,

I've experienced a weird behavior while merging our YAML files.
## npm list -g @alexlafroscia/yaml-merge
```
/usr/lib
└── @alexlafroscia/yaml-merge@1.0.4 
```

Lets assume we have those 2 files:

# test1.yaml
```yaml
foo:
bar:
  baz: "test"
```

# test2.yaml
```yaml
foo:
  baz: "test123"
bar:
  qoo: "ooq"
```

If you merge these files in the following order, anything seems to be fine:
## yaml-merge test2.yaml test1.yaml
```yaml
foo:
  baz: test123
bar:
  baz: test
  qoo: ooq
```

But if you merge the file in the opposite order, you'll get the following (invalid) merged file:
## yaml-merge test1.yaml test2.yaml
```yaml
foo: null
bar:
  qoo: ooq
  baz: test
```

As we are not totally in control of the order of our files, I would assume that the merging works as expected in the first example. Therefore, I consider this a bug?

Hope one can fix this as we probably might running into this again. As a quickfix, I just dropped the empty `foo:` statement as we do not provide informations for that object.
