### ISSUE TITLE
Keep leading zeros for ints and numbers

### ISSUE THREAD

**Issue by adaliszk** [alexlafroscia/yaml-merge#96]
## Problem
While using a merge on YAML files, for the most part, the library does merge correctly, however, when integers and numbers are in a format where there are leading zeros then it converts that into a format without one.

In my case, I wanted to merge butane files (that are YAML files with a specific schema) for Fedora CoreOS but it failed on the storage.files.#.mode where the property has to be in an octal integer format, having a leading zero for most use-cases.

## Example
file1.yaml
```yaml
storage:
  files:
    - path: /some/file1
      mode: 0644
      contents:
        inline: "..."
```

file2.yaml
```yaml
storage:
  files:
    - path: /some/file2
      mode: 0600
      contents:
        inline: "..."
```

```bash
yaml-merge file1.yaml file2.yaml
```

## Current behaviour
the generated output:
```yaml
storage:
  files:
    - path: /some/file1
      mode: 644
      contents:
        inline: "..."
    - path: /some/file2
      mode: 600
      contents:
        inline: "..."
```

## Expected behaviour
the generated output:
```yaml
storage:
  files:
    - path: /some/file1
      mode: 0644
      contents:
        inline: "..."
    - path: /some/file2
      mode: 0600
      contents:
        inline: "..."
```

## Workarounds
- I have tried to wrap up the octane number in apostrophes, but then the file fails on a schema validation
